// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwzvelmoikkelnagnqen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3enZlbG1vaWtrZWxuYWducWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NzA1NDMsImV4cCI6MjA1NjA0NjU0M30.OOGV9-Tvn5kiDbW34vc_DrCY-UtR8X3LmyqUOxLNLok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);